version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
{% include "pack/partial.yml" %}
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: {{ wordpressuser }}
      MYSQL_PASSWORD: {{ wordpresspassword }}
  wordpress_2:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8001:80"
{% include "pack/partial.yml" %}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: {{ wordpressuser }}
      WORDPRESS_DB_PASSWORD: {{ wordpresspassword }}
    secrets:
      - source: {{ external_secret("my_secret_data_2")}}
        target: my_secret

volumes:
  db_data: {}

