version: '3.3'

services:
  db:
    image: {{ mysql.image.repository }}:{{ mysql.image.tag }}
    volumes:
      - db_data:/var/lib/mysql
{% include "partial.yml" %}
      MYSQL_ROOT_PASSWORD: {{ mysql.root_password }}
      MYSQL_DATABASE: {{ database }}
      MYSQL_USER: {{ user }}
      MYSQL_PASSWORD: {{ password }}
  wordpress_2:
    depends_on:
      - db
    image: {{ wordpress.image.repository }}:{{ wordpress.image.tag }}
    ports:
      - "8001:80"
{% include "partial.yml" %}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: {{ wordpress.user }}
      WORDPRESS_DB_PASSWORD: {{ password }}
    secrets:
      - source: {{ secret_from_value("wordpress.my_secret_data")}}
        target: my_secret

volumes:
  db_data: {}